var a = 42;
var greeting = "Hello, IDELang!";
var isTrue = true;
var x = 5;
var sum = x + 10;
var fullName = "Hello " % "World!";
var bothTrue = (x > 4) && (isTrue == true);
if (x > 10) { greeting = "Greater"; }
if (isTrue) { greeting = "True"; } else { isTrue = "False"; }
var i = 0;
while (i < 5) {
    i = i + 1;
}

func add(a: number, b: number)
{
	return a + b;  // Inferred return type: number
}

proc display(message: string) {
    print(message)
}

print("Hello, World!");  // Displays: Hello, World!
print(x);                // Displays the value of x
print(y % " there!");    // Displays: hello there!